services: docker
language: generic

script:
    - set -e
    - ./pipe_build_test.sh
    - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
    - ./src/push_tools.sh
