sudo: required
services: docker

script:
    - ./build.sh
    # TODO: run tests

    # example runs
    - ./run_build_image.sh

    # push image to dockerhub
    - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
    - ORG_NAME=cyberdojofoundation
    - TAG_NAME=$(basename ${TRAVIS_REPO_SLUG})
    - NAME=${ORG_NAME}/${TAG_NAME}
    #- docker push ${NAME}
