services: docker
language: generic
branches:
  only:
  - master
git:
  depth: 5

script:
    - set -e
    - ./src/build_tools.sh
    - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
    - ./src/push_tools.sh
    - ./pipe_build_test.sh && ./sh/push_image_builder.sh
