sudo: required
services: docker

script:
    - ORG_NAME=cyberdojofoundation
    - TAG_NAME=$(basename ${TRAVIS_REPO_SLUG})
    - NAME=${ORG_NAME}/${TAG_NAME}
    - docker build -t ${NAME} .

    # TODO: run tests

    # example run
    - docker run --rm -it ${NAME} ./of.rb ALPHA

    # push image to dockerhub
    - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
    - docker push ${NAME}
