services: docker
language: generic

script:
    - set -e
    - ./src/build_tools.sh
    - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
    - docker push cyberdojo/dockerfile_augmenter
    - docker push cyberdojo/image_namer
    - docker push cyberdojo/dependents_notifier
    -
    - ./pipe_build_test.sh && ./sh/push_image_builder.sh
