version: 2
jobs:
  build-publish-trigger:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build tools and test them
          command: |
            set -e
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            ./pipe_build_up_test.sh
      - run:
          name: Publish tools on dockerhub
          command: |
            set -e
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            ./src/push_tools.sh

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-languages-context
          filters:
            branches:
              only:
                  - master
